function install()
% Function to install all third party dependencies

installers = {...
  helpers.VlFeatInstaller(),...
  helpers.Installer(), ...
  datasets.vggAffineDataset(), ...
  benchmarks.repeatabilityBenchmark(), ...
  benchmarks.matchingBenchmark(), ...
  benchmarks.kristianEvalBenchmark(), ...
  localFeatures.vggAffine(), ...
  localFeatures.vggMser(), ...
  localFeatures.sfop()
  %localFeatures.cmpHessian(), ...
  };

% TODO solve if the reterival dataset sould be donwloaded

for installer=installers
  installer{:}.installDeps();
end