function install()
% Install benchmarks

installers = {...
  helpers.VlFeatInstaller('0.9.14'),...
  helpers.Installer(), ...
  benchmarks.repeatabilityBenchmark(), ...
  benchmarks.kristianEvalBenchmark()
  };

for installer=installers
  installer{:}.install();
end